services:
    bundle:
        image: node
        volumes:
            - .:/code
        environment: 
            - NODE_ENV=development
        working_dir: /code
        entrypoint: npm
        command: start
    styles:
        image: node
        volumes:
            - .:/code
        working_dir: /code
        entrypoint: npm
        command: run start-styles